# Generated by Django 4.0.2 on 2022-02-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_alter_gi_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gi',
            name='photo',
        ),
    ]
