version: "3"

services:
  backend:
    image: eakyoungyu/ddobok_backend
    build:
      context: ./backend
      shm_size: "3gb"
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    image: seokyoungyu/jiujitsu-gi_frontend
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build
  nginx:
    image: seokyoungyu/nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
