version: "3"

services:
  backend:
    image: eakyoungyu/ddobok_backend
    env_file:
      - backend/.env
    build:
      context: ./backend
      shm_size: "3gb"
    ports:
      - "8000:8000"
  frontend:
    image: seokyoungyu/jiujitsu-gi_frontend:2.2.0
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build
  nginx:
    # image: seokyoungyu/nginx
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  react_build: {}
