# Generated by Django 4.0.2 on 2022-02-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_alter_gi_photo_photo'),
        ('brands', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='gis',
            field=models.ManyToManyField(blank=True, related_name='brands', to='gis.Gi'),
        ),
    ]
