# Generated by Django 4.0.2 on 2022-02-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_alter_gi_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gi',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gi_photos'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='gi_photos')),
                ('gi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gis.gi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
